platform: linux
image_resource:
  type: docker-image
  source:
    repository: kaiwinter/docker-java8-maven

inputs:
  - name: source-code

run:
  path: "mvn"
  args: ["clean", "install"]
params:
  MAVEN_BASEDIR: source-code
